### Code Aliases ###
set(LIB_STATIC_NAME "${LOCAL_CMAKE_PROJECT_NAME}")
set(${LOCAL_CMAKE_PROJECT_NAME}_STATIC_LIB "${CMAKE_CURRENT_BINARY_DIR}/${LOCAL_CMAKE_PROJECT_NAME}/src/lib${LIB_STATIC_NAME}.a")
set(${LOCAL_CMAKE_PROJECT_NAME}_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/${LOCAL_CMAKE_PROJECT_NAME}/include")
set(LIB_SHARED_NAME "${LOCAL_CMAKE_PROJECT_NAME}")
set(TEST_NAME "${LOCAL_CMAKE_PROJECT_NAME}_test")
