##########################################
# CXXFLAGS/LFLAGS external configuration #
##########################################
if(CXXFLAGS_RELEASE_FLAG)
    set(CMAKE_BUILD_TYPE "RELEASE")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2 -ggdb3")
    message(STATUS "${LOCAL_CMAKE_PROJECT_NAME}:  release CXXFLAGS [-O2 -ggdb3]")
elseif(CXXFLAGS_NATIVE_FLAG)
    set(CMAKE_BUILD_TYPE "NATIVE")
    if(APPLE)
        message(FATAL_ERROR "CXXFLAGS_NATIVE_FLAG, linking time optimization, not configured for macOS")
    endif()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2  -flto -march=native")
    set(CMAKE_AR  ${SPECIAL_AR})
    set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
    set(CMAKE_CXX_ARCHIVE_FINISH   true)
    message(STATUS "${LOCAL_CMAKE_PROJECT_NAME}:  native CXXFLAGS [-O2 -flto -march=native]")
elseif(CXXFLAGS_OPTIMIZED_FLAG)
    set(CMAKE_BUILD_TYPE "OPTIMIZED")
    if(APPLE)
        message(FATAL_ERROR "CXXFLAGS_OPTIMIZED_FLAG, linking time optimization, not configured for macOS")
    endif()
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2 -march=haswell -flto -fuse-ld=gold -fuse-linker-plugin")
    set(CMAKE_AR ${SPECIAL_AR})
    set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
    set(CMAKE_CXX_ARCHIVE_FINISH   true) 
    message(STATUS "${LOCAL_CMAKE_PROJECT_NAME}:  optimized CXXFLAGS [-O2 -march=haswell -flto -fuse-ld=gold -fuse-linker-plugin]")
else() # default --> standard
    set(CMAKE_BUILD_TYPE "STANDARD")
    set(CXXFLAGS_STANDARD_FLAG true)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0  -ggdb3 -Wunused")
    message(STATUS "${LOCAL_CMAKE_PROJECT_NAME}:  standard CXXFLAGS [-O0 -ggdb3 -Wunused]")
endif()
if(SANITIZE_ADDRESS_FLAG)
    set(CMAKE_BUILD_TYPE "SANITIZE_ADDRESS ${CMAKE_BUILD_TYPE}")
    set(CMAKE_COMPILER_FLAGS "${CMAKE_COMPILER_FLAGS} -fsanitize=address -fno-omit-frame-pointer")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=address -fno-omit-frame-pointer")
elseif(SANITIZE_UNDEFINED_FLAG)
    set(CMAKE_BUILD_TYPE "SANITIZE_UNDEFINED ${CMAKE_BUILD_TYPE}")
    set(CMAKE_COMPILER_FLAGS "${CMAKE_COMPILER_FLAGS} -fsanitize=undefined -fno-omit-frame-pointer")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=undefined -fno-omit-frame-pointer")
    set(CMAKE_LINKER_FLAGS "${CMAKE_LINKER_FLAGS}  -fsanitize=undefined")
endif()

message(STATUS "${LOCAL_CMAKE_PROJECT_NAME} C++ compiler:    ${CMAKE_COMPILER_FLAGS}")
message(STATUS "${LOCAL_CMAKE_PROJECT_NAME} C++ flags:    ${CMAKE_CXX_FLAGS}")
message(STATUS "${LOCAL_CMAKE_PROJECT_NAME} linker flags: ${CMAKE_LINKER_FLAGS}")

